FROM node:18.13.0-alpine3.16

RUN apk update

WORKDIR /app

COPY package.json /app

COPY . /app

RUN npm install
RUN npx prisma db push --schema="./prisma/schema.prisma"
RUN npx prisma generate --schema="./prisma/schema.prisma"

EXPOSE 3000

CMD [ "npm", "start" ]